# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /usr/src/app

RUN pip install --no-cache-dir flask sentence-transformers torch
# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV MODEL_NAME=BAAI/bge-m3

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]